title: Welcome to my Blog
author: innthomas
email: innthomas@tutanota.com
description: > # this means to ignore newlines until "baseurl:"
  You are welcome to my awesome blog. Feel free to check around often for updates.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
# add theme
theme: minima
